print("My name is Shaelyn")
print("I was born in August")
print("FAVES")
print("food: pasta")
print("music: pop & musicals")
print("sign: Virgo")

print("My name is Kelsey")
print("I was born in June")
print("My favorite food is mac and cheese, but I also really love sushi")
print("My favorite type of music is alternative")
print("My astrological sign is gemini")
print("I am five feet tall with an extra inch")
print("I'm afraid of heights and failure")

print("Hi Shaelyn!!")
